name: ChestRandomizer
author: Infuzion
version: 1.1
database: false

main: src.infuzion.chest.randomizer.main
description: A plugin that allows the randomization of chests for minigames such as Hunger games, or skywars.
website: http://dev.bukkit.org/bukkit-plugins/chest-randomizer/

commands:
  chestrandomizer:
    description: The main command of this plugin
    aliases: [cr]
    permission: cr.randomize
    usage: /chestrandomizer

permissions:
  cr.reload:
    description: Allows the use of /cr reload
    default: op
  cr.randomize:
    description: Allows the use of /cr randomize
  cr.access:
    description: Allows the use of /cr
  cr.*:
    description: Gives access to all chest randomizer commands
    default: op
    children:
      cr.randomize: true
      cr.reload: true
      cr.access: true